---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_pip: true
  ansible_version: 2.0.2.0
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_ansible_source: false
  require_chef_for_busser: true
  require_ruby_for_busser: false
  ansible_sudo: false
  ansible_check: false
  idempotency_test: true
  update_package_repos: false
#  requirements_path: requirements.yml

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
